name: CI

on:
  push:
    branches: [ "main" ] # Sequence of patterns matched against refs/heads
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# All steps in a job are executed in a single VM
# Information can be exchanged within the same job
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}'

      - id: set-up-cloud-sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - id: 'deploy'
        run: |
          gcloud functions deploy jwt-publication \
          --gen2 --trigger-http --runtime nodejs20 --no-allow-unauthenticated \
          --region us-central1 \
          --entry-point jwtPublication
